definitions:
  dtos.ExecLogsResponse:
    properties:
      message:
        type: string
    type: object
  dtos.RunAllResponse:
    properties:
      message:
        type: string
    type: object
  dtos.RunGroupResponse:
    properties:
      message:
        type: string
    type: object
  dtos.RunResponse:
    properties:
      message:
        type: string
    type: object
  dtos.SetResponse:
    properties:
      message:
        type: string
    type: object
  dtos.StatusResponse:
    properties:
      message:
        type: string
    type: object
  dtos.StopAllResponse:
    properties:
      message:
        type: string
    type: object
  dtos.StopGroupResponse:
    properties:
      message:
        type: string
    type: object
  dtos.StopResponse:
    properties:
      message:
        type: string
    type: object
  dtos.UnsetResponse:
    properties:
      message:
        type: string
    type: object
  orchestrator.Status:
    properties:
      auto_restart:
        type: boolean
      group:
        type: integer
      id:
        type: string
      name:
        type: string
      pid:
        type: integer
      running:
        type: boolean
    type: object
info:
  contact: {}
  description: This is an API that controls running processes.
  title: orchestrator-api
  version: 0.0.1
paths:
  /execlogs:
    get:
      description: This endpoint tries to get the logs of an executable that is set
        in the orchestrator.
      parameters:
      - description: UUID of the executable to get logs
        format: uuid
        in: query
        name: id
        required: true
        type: string
      - description: Type of logs to get
        in: query
        name: type
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ExecLogsResponse'
      summary: Get the logs of an executable
      tags:
      - orchestrator
  /run:
    get:
      description: This endpoint tries to run an executable that is set in the orchestrator.
      parameters:
      - description: UUID of the executable to run
        format: uuid
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.RunResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.RunResponse'
      summary: Run an executable
      tags:
      - orchestrator
  /runall:
    get:
      description: This endpoint tries to run all the executables that are set in
        the orchestrator.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.RunAllResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.RunAllResponse'
      summary: Run all the executables
      tags:
      - orchestrator
  /rungroup:
    get:
      description: This endpoint tries to run a group of executables that are set
        in the orchestrator.
      parameters:
      - description: Group ID to run
        in: query
        name: group
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.RunGroupResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.RunGroupResponse'
      summary: Run a group of executables
      tags:
      - orchestrator
  /set:
    get:
      description: This endpoint sets the executables in the orchestrator. In order
        to set the executables again, all processes must be stopped and unset.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.SetResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.SetResponse'
      summary: Set the executables
      tags:
      - orchestrator
  /status:
    get:
      description: This endpoint returns the status of the executables that are set
        in the orchestrator.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/orchestrator.Status'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.StatusResponse'
      summary: Return the status of the executables
      tags:
      - orchestrator
  /stop:
    get:
      description: This endpoint tries to stop an executable that is set in the orchestrator.
      parameters:
      - description: UUID of the group to stop
        format: uuid
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.StopResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.StopResponse'
      summary: Stops an executable
      tags:
      - orchestrator
  /stopall:
    get:
      description: This endpoint tries to stop all the executables that are set in
        the orchestrator.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.StopAllResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.StopAllResponse'
      summary: Stops all the executables
      tags:
      - orchestrator
  /stopgroup:
    get:
      description: This endpoint tries to stop a group of executables that are set
        in the orchestrator.
      parameters:
      - description: Group ID to stop
        in: query
        name: group
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.StopGroupResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.StopGroupResponse'
      summary: Stops a group of executables
      tags:
      - orchestrator
  /unset:
    get:
      description: This endpoint unsets the executables in the orchestrator. In order
        to unset the executables, all processes must be stopped.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.UnsetResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.UnsetResponse'
      summary: Unset the executables
      tags:
      - orchestrator
swagger: "2.0"
